name: 'openledger'
version: '1.0.0'
config-version: 2

profile: 'openledger'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  openledger:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: incremental