version: 2

sources:
  - name: openledger
    database: OPENLEDGER
    schema: RAW
    tables:
      - name: transactions
        loaded_at_field: event_time
        freshness:
          warn_after: {count: 24, period: hour}
          # error_after: {count: 48, period: hour}
        description: "Raw transaction logs from the core banking ledger."
      - name: ledger_entries
        loaded_at_field: event_time
      - name: settlements
        loaded_at_field: settlement_date
        freshness:
          warn_after: {count: 24, period: hour}