version: 2

models:
  - name: int_ledger_integrity
    description: 'Confirms that debits == credits'
    columns:
      - name: transaction_id
        description: 'Primary key'
        tests:
          - unique
          - not_null
      - name: total_debits
        description: 'Sum of debits'
      - name: total_credits
        description: 'Sum of credits'
      - name: balance_delta
        description: 'Difference between debits and credits, should be 0.'
      - name: integrity_status
        description: 'Shows if ledger is balanced'
        tests:
          - accepted_values:
              values: ['BALANCED', 'UNBALANCED']
              severity: warn