version: 2

models:
  - name: fct_transactions
    description: 'Central fact table for reconciliation'
    columns:
      - name: transaction_id
        description: 'Primary key'
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: user_id
        description: 'Foreign key for User'
        tests:
          - not_null:
              severity: warn
      - name: internal_amount
        description: 'Transaction amount from local ledger'
        tests:
          - not_null:
              severity: warn
      - name: ledger_integrity
        description: 'Shows if ledger is balanced or not'
        tests:
          - accepted_values:
              values: ['BALANCED', 'UNBALANCED', 'UNKNOWN']
              severity: warn